Repository F3T1W/EldenTracker, pull requests merged in 2023-08, with the labels that each got.

#1 Refactored/Cleaned appended experimental events with TODO
  MainPage.xaml
  MainPage.xaml.cs
  Resources/Map/IMap.cs
  Resources/Map/Map.cs
Labels: enhancement, refactoring

#3 Made default scrolling position per launch
  MainPage.xaml.cs
Labels: enhancement

#4 Added left side panel
  App.xaml
  MainPage.xaml
  MainPage.xaml.cs
  Resources/Map/IMap.cs
  Resources/Map/Map.cs
Labels: enhancement

#6 Slight xaml code-style changes
  MainPage.xaml
  MainPage.xaml.cs
Labels: refactoring

#7 First PointOfInterest revision
  EldenTracker.csproj
  MainPage.xaml
  MainPage.xaml.cs
  Resources/PointsOfInterest/Images/SoG.png
  Resources/PointsOfInterest/PointOfInterest.cs
  Resources/PointsOfInterest/PointOfInterestControl.xaml
  Resources/PointsOfInterest/PointOfInterestControl.xaml.cs
Labels: enhancement

#10 Create dotnet-desktop.yml
  .github/workflows/dotnet-desktop.yml
Labels: enhancement

#9 Realized creating PointOfInterest by clicking RMB
  EldenTracker.csproj
  MainPage.xaml
  MainPage.xaml.cs
  Resources/PointsOfInterest/Images/CustomPoint.png
  Resources/PointsOfInterest/Images/DefaultPoint.png
  Resources/PointsOfInterest/PointOfInterest.cs
  Resources/PointsOfInterest/PointOfInterestType.cs
Labels: enhancement

#17 Feature/popupPoI
  MainPage.xaml
  MainPage.xaml.cs
  Resources/PointsOfInterest/PointOfInterest.cs
  Resources/PointsOfInterest/PointOfInterestControl.xaml.cs
Labels: enhancement

#21 Refactored project structure via introducing UI folder and UI controls into it
  App.xaml
  EldenTracker.csproj
  MainPage.xaml
  MainPage.xaml.cs
  Modals/MapPage.xaml
  Modals/Utils/ImageScroll.cs
  Modals/WikiPage.xaml.cs
  Model/PointOfInterest.cs
  UI/Controls/PointOfInterest.xaml
  UI/Controls/PointOfInterest.xaml.cs
  UI/Controls/ScrollableImage.xaml
  UI/Controls/ScrollableImage.xaml.cs
  UI/Pages/MapPage.xaml
  UI/Pages/MapPage.xaml.cs
  UI/Pages/WikiPage.xaml
  UI/Pages/WikiPage.xaml.cs
  UI/Popups/PointDialog.xaml
  UI/Popups/PointDialog.xaml.cs
Labels: enhancement, refactoring

#22 Revert "Refactored project structure via introducing UI folder and UI controls into it"
  App.xaml
  EldenTracker.csproj
  MainPage.xaml
  MainPage.xaml.cs
  Modals/MapPage.xaml
  Modals/MapPage.xaml.cs
  Modals/PointOfInterestControl.xaml
  Modals/PointOfInterestControl.xaml.cs
  Modals/Popups/PointDialog.xaml
  Modals/Popups/PointDialog.xaml.cs
  Modals/Utils/ImageScroll.cs
  Modals/WikiPage.xaml
  Modals/WikiPage.xaml.cs
  Model/PointOfInterest.cs
  UI/Controls/ScrollableImage.xaml
  UI/Controls/ScrollableImage.xaml.cs
  UI/Pages/MapPage.xaml
  UI/Pages/WikiPage.xaml.cs
Labels: bug, invalid, wontfix
